language: perl
perl:
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24.0-thr"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
  - "blead"
sudo: false
matrix:
  allow_failures:
    - perl: blead
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
