# Executes test, once with AnyEvent (which can be used if it is installed,
# but is not part of the dependency chain) and with just the dependency
# chain.
name: Execute tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-with-anyevent:
    uses: jmaslak/github_workflows/.github/workflows/cpan-dzil-test-with-anyevent.yml@v2
  build-and-test-without-anyevent:
    uses: jmaslak/github_workflows/.github/workflows/cpan-dzil-test.yml@v2
